# Generated by Django 4.0.3 on 2022-04-06 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todays_meal', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=15, max_digits=15, null=True)),
                ('total_meal', models.IntegerField(blank=True, default=0, null=True)),
                ('person_spend', models.FloatField(blank=True, default=0, null=True)),
                ('spend_total', models.FloatField(blank=True, default=0, null=True)),
                ('deposit', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('mess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mess')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
