# Generated by Django 4.0.3 on 2022-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountspend',
            name='amounts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amountspend',
            name='spend_on',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
