# Generated by Django 4.0.3 on 2022-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_amountspend_list_spend_alter_amountspend_amounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdeposit',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
